package domain.model;

public enum SpecificType {
    Ball,
    FireBall,
    FireBallExplosion,
    ChemicalBall,
    Paddle,
    SimpleBrick,
    MineBrick,
    HalfMetalBrick,
    WrapperBrick,
    CooperativeAlien,
    ProtectingAlien,
    RepairingAlien,
    ConfusedDrunkAlien,
    DrunkAlien,
    Explosion,
    Laser,
    DestructiveLaserGun,
    GangOfBallsPowerup,
    TallerPaddlePowerup,
    MagnetPowerup,
    FireBallPowerup,
    ChemicalBallPowerup,
    AlienBeam,
}
